version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: tailwindcss
    versions:
    - 2.0.2
    - 2.0.3
    - 2.0.4
    - 2.1.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
